set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)

if(NOT DEFINED THEOS_SDK_PATH)
    if(DEFINED ENV{THEOS})
        set(THEOS_SDK_PATH $ENV{THEOS})
    elseif(EXISTS "$ENV{HOME}/theos/sdks")
        set(THEOS_SDK_PATH "$ENV{HOME}/theos/sdks")
    elseif(EXISTS "$ENV{USERPROFILE}/theos/sdks")
        set(THEOS_SDK_PATH "$ENV{USERPROFILE}/theos/sdks")
    else()
        set(THEOS_SDK_PATH "${CMAKE_SOURCE_DIR}/theos-sdks")
    endif()
endif()

if(NOT DEFINED CMAKE_C_COMPILER)
    find_program(CMAKE_C_COMPILER arm64-apple-ios-clang)
    if(NOT CMAKE_C_COMPILER)
        find_program(CMAKE_C_COMPILER clang)
    endif()
endif()

if(NOT DEFINED CMAKE_CXX_COMPILER)
    find_program(CMAKE_CXX_COMPILER arm64-apple-ios-clang++)
    if(NOT CMAKE_CXX_COMPILER)
        find_program(CMAKE_CXX_COMPILER clang++)
    endif()
endif()

set(CMAKE_OSX_SYSROOT "${THEOS_SDK_PATH}/iPhoneOS.sdk" CACHE PATH "iOS SDK root")
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "iOS architectures")
set(CMAKE_OSX_DEPLOYMENT_TARGET "13.0" CACHE STRING "iOS deployment target")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -target arm64-apple-ios13.0 -fuse-ld=lld" CACHE STRING "C flags for iOS ARM64")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -target arm64-apple-ios13.0 -fuse-ld=lld" CACHE STRING "CXX flags for iOS ARM64")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
